// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/razedwell/traxex/services/auth/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockSessionStore is an autogenerated mock type for the SessionStore type
type MockSessionStore struct {
	mock.Mock
}

type MockSessionStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionStore) EXPECT() *MockSessionStore_Expecter {
	return &MockSessionStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, refresh
func (_m *MockSessionStore) Delete(ctx context.Context, refresh string) error {
	ret := _m.Called(ctx, refresh)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, refresh)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSessionStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - refresh string
func (_e *MockSessionStore_Expecter) Delete(ctx interface{}, refresh interface{}) *MockSessionStore_Delete_Call {
	return &MockSessionStore_Delete_Call{Call: _e.mock.On("Delete", ctx, refresh)}
}

func (_c *MockSessionStore_Delete_Call) Run(run func(ctx context.Context, refresh string)) *MockSessionStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSessionStore_Delete_Call) Return(_a0 error) *MockSessionStore_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionStore_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockSessionStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, refresh
func (_m *MockSessionStore) Get(ctx context.Context, refresh string) (domain.Session, error) {
	ret := _m.Called(ctx, refresh)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Session, error)); ok {
		return rf(ctx, refresh)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Session); ok {
		r0 = rf(ctx, refresh)
	} else {
		r0 = ret.Get(0).(domain.Session)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refresh)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSessionStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - refresh string
func (_e *MockSessionStore_Expecter) Get(ctx interface{}, refresh interface{}) *MockSessionStore_Get_Call {
	return &MockSessionStore_Get_Call{Call: _e.mock.On("Get", ctx, refresh)}
}

func (_c *MockSessionStore_Get_Call) Run(run func(ctx context.Context, refresh string)) *MockSessionStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSessionStore_Get_Call) Return(_a0 domain.Session, _a1 error) *MockSessionStore_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionStore_Get_Call) RunAndReturn(run func(context.Context, string) (domain.Session, error)) *MockSessionStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, s, ttl
func (_m *MockSessionStore) Save(ctx context.Context, s domain.Session, ttl time.Duration) error {
	ret := _m.Called(ctx, s, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Session, time.Duration) error); ok {
		r0 = rf(ctx, s, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockSessionStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - s domain.Session
//   - ttl time.Duration
func (_e *MockSessionStore_Expecter) Save(ctx interface{}, s interface{}, ttl interface{}) *MockSessionStore_Save_Call {
	return &MockSessionStore_Save_Call{Call: _e.mock.On("Save", ctx, s, ttl)}
}

func (_c *MockSessionStore_Save_Call) Run(run func(ctx context.Context, s domain.Session, ttl time.Duration)) *MockSessionStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Session), args[2].(time.Duration))
	})
	return _c
}

func (_c *MockSessionStore_Save_Call) Return(_a0 error) *MockSessionStore_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionStore_Save_Call) RunAndReturn(run func(context.Context, domain.Session, time.Duration) error) *MockSessionStore_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionStore creates a new instance of MockSessionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionStore {
	mock := &MockSessionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
